# Generated by Django 4.0.3 on 2022-03-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('writer', models.CharField(max_length=255)),
                ('synopsis', models.TextField(max_length=1000)),
                ('genre', models.CharField(max_length=100)),
                ('release_date', models.DateTimeField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
